config/routes.rb
Rails.application.routes.draw do
  resources :episodes
  devise_for :users
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :episodes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]
  # GET /episodes or /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1 or /episodes/1.json
  def show; end

  # GET /episodes/new
  def new
    # @episode = Episode.new
    @episode = current_user.episodes.build
  end

  # GET /episodes/1/edit
  def edit; end

  # POST /episodes or /episodes.json
  def create
    # @episode = Episode.new(episode_params)
    @episode = current_user.episodes.build(episode_params)
    respond_to do |format|
      if @episode.save
        format.html { redirect_to episode_url(@episode), notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1 or /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to episode_url(@episode), notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1 or /episodes/1.json
  def destroy
    @episode.destroy

    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @episode = current_user.episodes.find_by(id: params[:id])
    redirect_to root_path, notice: 'Not authorized to Edit this Event' if @episode.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_episode
    @episode = Episode.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def episode_params
    params.require(:episode).permit(:title, :description, :start_time, :end_time)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @episodes = Episode.where(
      start_time: Time.now.beginning_of_month.beginning_of_week..Time.now.end_of_month.end_of_week
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/episodes/_episode.html.erb
<div id="<%= dom_id episode %>">
  <p>
    <strong>Title:</strong>
    <%= episode.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= episode.description %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= episode.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= episode.end_time %>
  </p>

</div>

app/views/episodes/_form.html.erb
<%= form_with(model: episode) do |form| %>
  <% if episode.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this Event from being saved:</h2>

      <ul>
        <% episode.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.datetime_field :start_time %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.datetime_field :end_time %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render "form", episode: @episode %>

<br>

<div>
  <%= link_to "Event detail", @episode %> |
  <%= link_to "Event list", episodes_path %>
</div>

app/views/episodes/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Episodes</h1>
<div id="episodes">
  <% @episodes.each do |episode| %>
    <% if episode.user == current_user %>
      <%= render episode %>
      <p>
        <%= link_to "Event detail", episode %>
      </p>
    <% end %>
  <% end %>
</div>
<% if current_user %>
  <%= link_to "New Event", new_episode_path %>
<% end %>

app/views/episodes/new.html.erb
<h1>New Event</h1>

<%= render "form", episode: @episode %>

<br>

<div>
  <%= link_to "Event list", episodes_path %>
</div>

app/views/episodes/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @episode %>
<% if current_user %>
  <div>
    <%= link_to "Edit this event", edit_episode_path(@episode) %> |
    <%= link_to "Event list", episodes_path %>
    <%= button_to "Delete Event", @episode, method: :delete %>
  </div>
<% end %>

app/views/home/index.html.erb
<div class= "container mt-5 text-center">
  <h1>Calendar</h1>
  <!-- <%= month_calendar() do |date| %>
    <div class = "day">
      <%= date.day %>
    </div>
  <% end %>
  -->
  <!-- <%= turbo_frame_tag 'calendar' do %> -->
  <%= month_calendar(events: @episodes) do |date, episodes| %>
    <%= date.day %>
    <% episodes.each do |episode| %>
      <% if current_user == episode.user %>
        <div class="card-header" >
          <div class="card-title">
            <%= link_to episode.title, episode %>
          </div>
        </div>
        <div class="card-body" >
          <p class="card-text">
            <%= episode.description %>
          </p>
        </div>
        <div class="card-footer" >
          <p class="card-text">
            From: <%= episode.start_time.strftime("%A, %d %B at %I:%M %p") %>
          </p>
          <p class="card-text">
            To: <%= episode.end_time.strftime("%A, %d %B at %I:%M %p") %>
          </p>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <!-- <% end %> -->
</div>

app/views/layouts/_alerts.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "JE", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Event list", episodes_path, class: "nav-link" %>
        </li>
        <% if current_user %>
        <li class="nav-item">
          <%= link_to "Create Event", new_episode_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item"> <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-primary mx-2" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SimpleCalendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "loginpage", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <time datetime="<%= start_date.strftime('%Y-%m') %>" class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></time>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title">
      <%= t('simple_calendar.week', default: 'Week') %>
      <%= calendar.week_number %>
      <% if calendar.number_of_weeks > 1 %>
        - <%= calendar.end_week %>
      <% end %>
    </span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>